---
title: "R Notebook"
output: html_notebook
---

```{r}
library(magrittr)
library(dplyr)
library(tidyselect)
library(tidyr)

```


```{r}
g <- replicate(4, rand_group(), simplify = FALSE)
lengths(g)
```

```{r}
df <- group_join(g)
head(df)
```

```{r}
unique_clone_df <- distinct(df)

unique_clontype_df <- distinct_at(unique_clone_df, all_of(vars(c("group", "rep_id", "clonotype"))))

sapply(list(df,unique_clone_df), nrow)
```

```{r}
cr_level <- unite(unique_clone_df, col = "id", c("group", "rep_id"), sep = "/") %>% 
  
  select_at(all_of(vars(c("clonotype", "id")))) %>% table


head(cr_level)
```

```{r}

clonotype_share_level <- unique_clontype_df %>% 

  select_at(all_of(vars(c("clonotype", "group")))) %>%
  
  table

head(clonotype_share_level)
```


```{r}
clonal_seq_share_level <- unique_clone_df %>% 

  select_at(all_of(vars(c("clone", "group")))) %>%
  
  table

head(clonal_seq_share_level)

```

```{r}

# CR-class for clonotype
sharing_samples <- rowSums(clonotype_share_level, na.rm = TRUE)
sharing_groups <- rowSums(clonotype_share_level != 0, na.rm = TRUE)

is_private <- sharing_samples == 1
is_public <- sharing_samples > 1
is_exclusive <- is_public & (sharing_groups == 1)
is_inclusive <- is_public & (sharing_groups > 1)

clonotype_sharing <- list(sample=sharing_samples, 
                          group=sharing_groups)

clonotype_cr_type <- list(private=is_private,
                          public=is_public,
                          exclusive=is_exclusive,
                          inclusive=is_inclusive)

print(sapply(clonotype_cr_type, sum))
print(sapply(clonotype_sharing, sum))

```

```{r}
# CR-class for clonal sequences
sharing_samples <- rowSums(clonal_seq_share_level, na.rm = TRUE)
sharing_groups <- rowSums(clonal_seq_share_level != 0, na.rm = TRUE)

is_private <- sharing_samples == 1
is_public <- sharing_samples > 1
is_exclusive <- is_public & (sharing_groups == 1)
is_inclusive <- is_public & (sharing_groups > 1)

clone_sharing <- list(sample=sharing_samples, 
                group=sharing_groups)

clone_cr_type <- list(private=is_private,
                        public=is_public,
                        exclusive=is_exclusive,
                        inclusive=is_inclusive)

print(sapply(clone_sharing, sum))
print(sapply(clone_cr_type, sum))

```


```{r}

share_ratio <- clonotype_sharing$sample/clonotype_sharing$group
clonotype_cr_ratio <- lapply(clonotype_cr_type, function(x) share_ratio[x])
print(sapply(clonotype_cr_ratio, mean))

share_ratio <- clone_sharing$sample/clone_sharing$group
clone_cr_ratio <- lapply(clone_cr_type, function(x) share_ratio[x])
print(sapply(clone_cr_ratio, mean))

```

```{r}

```










