---
title: "crtcr-init"
author: "Ido Hasson"
date: "2022-11-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GitHub installation (temporary repository)
## CRAN installation (unavailable at the moment)

```{r results='hide', message=FALSE, warning=FALSE}
devtools::install_github("idohasson/crtcr")
```

```{r}
library("crtcr")
lsf.str("package:crtcr")
```

list of random CDR3 NT sequences

```{r}

rep_group <- rand_group(3)

print(rep_group[[1]][1:3])

lengths(rep_group)

```
```{r}
group_list <- list(pre_cancer=rand_group(),
                   cancer=rand_group(), 
                   control=rand_group())
lapply(group_list, lengths)
```

rearrange input data-set

```{r}

group_df <- group_join(group_list)

head(group_df)

```

```{r}
share_tbl <- share_table(group_df, "clonotype", "group", "rep_id")

rand_share <- share_tbl[sample.int(nrow(share_tbl), 10),]
rand_share
```

```{r}

cr_vec <- cr_class(rand_share)

as.data.frame(cr_vec)

```

```{r}
m <- 
matrix( c(
  c(1,0,1,0),
  c(2,0,0,0),
  c(1,0,0,0),
  c(0,0,0,0)), 
  4, byrow = TRUE, dimnames = list(paste0("scenario", seq(4)) ,
                                   paste0("group", seq(4))))

cbind.data.frame(m, CR_class=cr_freq_class(m))
```

```{r}
share_vec <- c(.1,.2,.3)

cr_freq_class(share_vec, min_freq=0.1, public_min = 0.2) 
cr_freq_class(share_vec, min_freq=0.25, public_min = 0.2) 
cr_freq_class(share_vec, min_freq=0.25, public_min = 0.4) 
cr_freq_class(share_vec, min_freq=0.4, public_min = 0.4) 

```


```{r}

```

