```{r}
library(sjmisc)
```


```{r}
groups <- replicate(3, rand_group(), simplify = FALSE)

if(!is_named(groups))
  groups <- setNames(groups, c("Pre-Cancer", "Cancer", "Control"))

groups_named <- map_if(groups, is_named, as.character, 
                  .else = ~ setNames(., seq_along(.)))

lapply(groups_named, lengths)
```
```{r}
clonotypes <- modify_depth(groups_named, 2, . %>% translate %>% unique)

clonotypes <-  clonotypes %>% 
  map_dfr(. %>%  unlist(use.names = FALSE) %>% 
            table %>% as.data.frame(), .id = "group") %>% 
  spread(key = "group", value = "Freq")

clonotypes %>% head
```

```{r}
share_table <- clonotypes[-1]

sharing_samples <- sums(n, na.rm = TRUE) <= 1
sharing_groups <- rowSums(is.na(clonotypes[-1])) <= length(share_table)-1
sharing_groups, sharing_samples
(sharing_samples <= 1) + (sharing_groups <= length(share_table)-1)
sharing_groups==1

```


```{r}

groups %>% map(distinct, )

subgroups <- map(groups, . %>% seq_along %>% set_names(x = .)) 

unlist(subgroups, recursive = FALSE)
map(subgroups, flatten_dfr, .id = "Subpopulations")


```

```{r}

cr_level <- table(groups[-2]) %>% t
cr_level %>% head
# share_level <- groups %>% distinct(clonotype, rep) %>%  with(table(clonotype)) 
```

```{r}

groups <- groups %>% mutate(group=gl(2,1, nrow(.), c("Cancer", "Control"))) %>% sample_n(1000)
head(groups)

```


```{r}

group_share <- distinct(groups, clonotype, group, clone) %>% 
  table %>% apply(c("clonotype", "group"), n_distinct)
group_share %>% head

```

```{r}


```


```{r}

groups %>% 
  lapply(. %>% unique %>% cbind.data.frame(nt=., aa=translate(.))) %>% 
  
  purrr::map_dfr()

rlang::set_names(groups, seq_along(groups)) %>%
  
  cbind.data.frame()
  
  purrr::map_dfr(translate, .id = "rep")

unlist(groups, use.names = FALSE) %>% table
```

