
```{r}
library("readr")
library("purrr")
library("dplyr")
library("tools")
```


```{r}

dir_path = "../data/Alpha/"

paths <- list.files(dir_path, full.names=TRUE)

group1_file_name_prefix <- "BRCA"
group2_file_name_prefix <- "Control"

group1_paths <- paths[startsWith(basename(paths), group1_file_name_prefix)]
group2_paths <- paths[startsWith(basename(paths), group2_file_name_prefix)]

names(group1_paths) <- file_path_sans_ext(basename(group1_paths))
names(group2_paths) <- file_path_sans_ext(basename(group2_paths))


mixcr_column_type <- cols(
  .default = col_logical(),
  cloneId = col_double(),
  cloneCount = col_double(),
  cloneFraction = col_double(),
  targetSequences = col_character(),
  targetQualities = col_character(),
  allVHitsWithScore = col_character(),
  allDHitsWithScore = col_character(),
  allJHitsWithScore = col_character(),
  allCHitsWithScore = col_character(),
  allVAlignments = col_character(),
  allDAlignments = col_character(),
  allJAlignments = col_character(),
  allCAlignments = col_character(),
  nSeqCDR3 = col_character(),
  minQualCDR3 = col_double(),
  aaSeqCDR3 = col_character(),
  refPoints = col_character()
)


group1 <- group1_paths %>% lapply(read_tsv, col_types = mixcr_column_type)
group2 <- group2_paths %>% lapply(read_tsv, col_types = mixcr_column_type)

```


```{r}

df1 <- group1 %>% 
  map_dfr(select, "cloneCount", "nSeqCDR3", "aaSeqCDR3", .id = "sample") %>% 
  mutate(group="Cancer")
df2 <- group2 %>% 
  map_dfr(select, "cloneCount", "nSeqCDR3", "aaSeqCDR3", .id = "sample") %>% 
  mutate(group="Control")

df <- rbind(df1, df2)

head(df)

```

# CR level The total amount of distinct nucleotide sequences encoding a particular phenotype within a sample.
# Sharing level - sharing level is simply measured as the number of animals sharing a specific sequence https://www.sciencedirect.com/science/article/pii/S2589004221000687#mmc1


<!-- ### number of clones shared between individuals -->
<!-- ### the number of different NT sequences encoding a specific AA sequence. -->

```{r}
df_cr_level <- df %>% 
  group_by(sample, aaSeqCDR3) %>% 
  add_tally(wt = n_distinct(nSeqCDR3), name = "CRlevel") %>% 
  ungroup(sample) %>% 
  add_tally(wt = n_distinct(sample), name = "SharingLevel") %>% 
  ungroup()

df_cr_level
```



```{r}
library("data.table")

# add_tally(wt = n_distinct(nSeqCDR3), name = "CRlevel")

cr_table <- as.data.table(df) %>% 
  .[,.(CRlevel=n_distinct(nSeqCDR3)), by=c("aaSeqCDR3", "sample")]


cr_table[cr_table$CRlevel>1,] %>% 
  sample_n(10) %>% 
  with(table(aaSeqCDR3, sample)) %>% 
  ftable

# cr_table %>% table("aaSeqCDR3", "sample")
# cr_table <-  %>% 
#   setorder(-CRlevel)

```

```{r}
cr_per_sample <- as.data.frame(cr_table) %>% 
  table %>% 
  colSums
cr_per_sample
# public_table <- cr_table %>% 
#   dcast(aaSeqCDR3 ~ sample, value.var = "CRlevel",fill = 0, margins = TRUE)
# 
# public_table %>% head

```
# simple two-way contingency table
with(airquality, table(cut(Temp, quantile(Temp)), Month))
```{r}
starts_with(colnames(public_table), "BRCA", )

dt[, paste0(cols, "_m") := lapply(.SD, mean), .SDcols = cols] 
```
```{r}

# head(cr_table) %>% table() %>% rowSums(dims = 2)


```


```{r}

library("data.table")

test <- df_cr_level[df_cr_level$CRlevel!=1,]

s <- test[sample(nrow(test), size = 10),] %>% 
  distinct(aaSeqCDR3, CRlevel, group, sample) %>%
  table %>% ftable
s
  
s[,,,]
# %>%
#   addmargins
s[,,"Control",]
s[,,"Cancer",]
dim(s)


s[,,"Sum"]

is_cancer <- s[,"Cancer","Sum"]>1
is_control <- s[,"Control","Sum"]>1


s[s[,"Sum","Sum"]>1,"Sum",]


df_cr_level %>% sample_n(10) %>% 
  select(nSeqCDR3, group, sample) %>%
  table %>%
  addmargins

```










